return {
    {
        "nvim-treesitter/nvim-treesitter",
        build = ":TSUpdate",
        main = "nvim-treesitter.configs",
        opts = {
            ensure_installed = {
                "bash",
                "c",
                "cpp",
                "c_sharp",
                "css",
                "diff",
                "dockerfile",
                "git_rebase",
                "git_config",
                "gitcommit",
                "gitignore",
                "go",
                "gomod",
                "gosum",
                "helm",
                "html",
                "java",
                "javascript",
                "json",
                "lua",
                "luadoc",
                "markdown",
                "markdown_inline",
                "php",
                "phpdoc",
                "powershell",
                "ssh_config",
                "sql",
                "terraform",
                "tmux",
                "tsv",
                "typescript",
                "vim",
                "vimdoc",
                "yaml",
                "zig",
            },
            auto_install = true,
            highlight = {
                enable = true,
                -- Some languages depend on vim's regex highlighting system (such as Ruby) for indent rules.
                --  If you are experiencing weird indenting issues, add the language to
                --  the list of additional_vim_regex_highlighting and disabled languages for indent.
                additional_vim_regex_highlighting = { "ruby" },
            },
            indent = { enable = true, disable = { "ruby" } },
        },
    },
}
